/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "photostockapi",
            "endpoint": "https://7mz9ohr1ba.execute-api.ap-northeast-1.amazonaws.com/deveieimon",
            "region": "ap-northeast-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ap-northeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "UserInfo-deveieimon",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "ImageInfo-deveieimon",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "ImageInfo-Tags-deveieimon",
            "region": "ap-northeast-1"
        },
        {
            "tableName": "TagNames-deveieimon",
            "region": "ap-northeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-northeast-1:6a33ef1c-0e16-4d09-8d65-e44b41d5657f",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_yAHZcL2O5",
    "aws_user_pools_web_client_id": "5a7pe96fm39kc8pk621jmkmi2l",
    "oauth": {
        "domain": "airiphoto.auth.ap-northeast-1.amazoncognito.com"
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "photostock-hosting-deveieimon",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "http://photostock-hosting-deveieimon.s3-website-ap-northeast-1.amazonaws.com"
};


export default awsmobile;
